"""Write the training rounds of .github/workflows/_train.yml (between the "rounds" markers).

GitHub Actions has no loops, and a reusable workflow calling another reusable workflow with a
matrix never starts, so each round is spelled out: N runners train from the same weights
(shard-rK), then their weights are averaged and validated (average-rK).

    python scripts/gen_train_rounds.py          # rewrite the file
    python scripts/gen_train_rounds.py --check  # fail if it is out of date (tests)
"""

from __future__ import annotations

import sys
from pathlib import Path

WORKFLOW = Path(__file__).resolve().parents[1] / ".github/workflows/_train.yml"
BEGIN = "  # --- rounds: generated by scripts/gen_train_rounds.py, do not edit by hand ---\n"
END = "  # --- end of generated rounds ---\n"
MAX_ROUNDS = 6

ROUND = """\
  shard-r{r}:
    needs: [{needs_shard}]
    if: ${{{{ !cancelled() && inputs.rounds >= {r} && needs.prepare.result == 'success'{prev_ok} }}}}
    runs-on: ubuntu-latest
    continue-on-error: true  # a lost runner only removes its share from the average
    timeout-minutes: 150  # round_minutes (at most 100) + setup, data and upload
    strategy:
      fail-fast: false
      matrix:
        shard: ${{{{ fromJSON(needs.prepare.outputs.shards) }}}}
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/ocr-train-setup
        with:
          paddleocr-ref: ${{{{ env.PADDLEOCR_REF }}}}
          paddleocr-dir: ${{{{ env.PADDLEOCR_DIR }}}}

      - uses: actions/download-artifact@v4
        with:
          name: ${{{{ inputs.product }}}}-prep
          path: ${{{{ env.WORK }}}}
{download_previous}
      - name: Train (round {r}, runner ${{{{ matrix.shard }}}})
        run: |
          source "$WORK/model.env"  # FUSE, FREEZE, GTC, LR of this training
          if [ -s "$WORK/start/avg.pdparams" ]; then export INIT_PARAMS="$WORK/start/avg.pdparams"
          elif [ -s "$WORK/resume/weights.pdparams" ]; then export INIT_PARAMS="$WORK/resume/weights.pdparams"; fi
          # constant LR per round, cosine over the rounds; warm-up at the start of every round
          # because each runner starts with a fresh optimizer
          export LR=$(python -c "import math; r, n, lr = {r}, ${{{{ inputs.rounds }}}}, $LR; print(f'{{lr * 0.5 * (1 + math.cos(math.pi * (r - 0.5) / n)):.6g}}')")
          export LR_CONST=1 NO_EVAL=1 WARMUP={warmup} FUSE FREEZE GTC
          SAMPLES=${{{{ inputs.lines }}}} CHUNK=${{{{ inputs.lines }}}} EPOCHS=100 BATCH=32 PRINT_STEP=10 \\
          SEED=$(( {r} * 1000 + ${{{{ matrix.shard }}}} )) TIME_BUDGET_MIN=${{{{ inputs.round_minutes }}}} \\
            training/vi_ocr/run_training.sh train
          grep -E "avg_batch_cost" "$WORK/output/train.log" | tail -1 || true

      - uses: actions/upload-artifact@v4
        with:
          name: ${{{{ inputs.product }}}}-r{r}-shard-${{{{ matrix.shard }}}}
          path: ${{{{ env.WORK }}}}/output/final.pdparams
          retention-days: 7

  average-r{r}:
    needs: [prepare, shard-r{r}]
    if: ${{{{ !cancelled() && inputs.rounds >= {r} && needs.shard-r{r}.result == 'success' }}}}
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/ocr-train-setup
        with:
          paddleocr-ref: ${{{{ env.PADDLEOCR_REF }}}}
          paddleocr-dir: ${{{{ env.PADDLEOCR_DIR }}}}

      - uses: actions/download-artifact@v4
        with:
          name: ${{{{ inputs.product }}}}-prep
          path: ${{{{ env.WORK }}}}

      - uses: actions/download-artifact@v4
        with:
          pattern: ${{{{ inputs.product }}}}-r{r}-shard-*
          path: shards

      - name: Average the runners' weights
        run: |
          mkdir -p avg
          found=$(ls shards/*/final.pdparams 2>/dev/null | wc -l)
          wanted=${{{{ inputs.runners }}}}
          echo "$found of $wanted runners finished round {r}"
          [ $((found * 2)) -ge "$wanted" ] || {{ echo "::error::fewer than half of the runners finished"; exit 1; }}
          python training/vi_ocr/average_params.py avg/avg.pdparams shards/*/final.pdparams

      - uses: actions/upload-artifact@v4
        with:
          name: ${{{{ inputs.product }}}}-avg-r{r}
          path: avg/avg.pdparams
          retention-days: 7

      - name: Validation after round {r}
        continue-on-error: true
        run: |
          source "$WORK/model.env"
          export FUSE
          EXPORT_PARAMS="$GITHUB_WORKSPACE/avg/avg.pdparams" training/vi_ocr/run_training.sh export
          sets=()
          for lang in ${{LANGS//,/ }}; do sets+=("$WORK/data/val_$lang"); done
          (cd training/vi_ocr && python evaluate.py --eval "${{sets[@]}}" --model "round {r}=$WORK/export" \\
            --model-name "$BASE_MODEL" --report "$WORK/val.md")
          {{ echo "### ${{{{ inputs.product }}}}: after round {r} of ${{{{ inputs.rounds }}}} (validation lines)"; cat "$WORK/val.md"; }} >> "$GITHUB_STEP_SUMMARY"

"""

DOWNLOAD_PREVIOUS = """
      - uses: actions/download-artifact@v4
        with:
          name: ${{{{ inputs.product }}}}-avg-r{prev}
          path: ${{{{ env.WORK }}}}/start
"""


def rounds() -> str:
    parts = [BEGIN]
    for r in range(1, MAX_ROUNDS + 1):
        prev = r - 1
        parts.append(
            ROUND.format(
                r=r,
                needs_shard="prepare" if r == 1 else f"prepare, average-r{prev}",
                prev_ok="" if r == 1 else f" && needs.average-r{prev}.result == 'success'",
                download_previous="" if r == 1 else DOWNLOAD_PREVIOUS.format(prev=prev),
                warmup="0.1" if r == 1 else "0.03",
            )
        )
    parts.append(END)
    return "".join(parts)


def render(text: str) -> str:
    start, end = text.index(BEGIN), text.index(END) + len(END)
    text = text[:start] + rounds() + text[end:]
    needs = ", ".join(["prepare"] + [f"average-r{r}" for r in range(1, MAX_ROUNDS + 1)])
    head, sep, tail = text.partition("  finalize:\n    needs: [")
    return head + sep + needs + tail[tail.index("]"):]


def main() -> int:
    current = WORKFLOW.read_text(encoding="utf-8")
    wanted = render(current)
    if "--check" in sys.argv[1:]:
        if current != wanted:
            print(f"{WORKFLOW} is out of date: run python scripts/gen_train_rounds.py")
            return 1
        return 0
    WORKFLOW.write_text(wanted, encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
